/* Données fictives de forfaits mobiles inwi Panorama (prototype) */

const CATEGORIES = {
  social: { label: "Réseaux sociaux", icon: "📱", color: "#FF3D81" },
  internet: { label: "Max Internet", icon: "🌐", color: "#00B8A9" },
  appels: { label: "Max Appels", icon: "📞", color: "#FF8A3D" },
  illimite: { label: "Illimité", icon: "♾️", color: "#8A3DFF" },
};

const PLANS = [
  {
    id: 1,
    name: "Social Start",
    category: "social",
    price: 49,
    internetGo: 2,
    internetLabel: "2 Go",
    callsLabel: "200 min",
    smsLabel: "100 SMS",
    mainBenefit: "Réseaux sociaux illimités",
    benefitIcon: "📱",
    socialUnlimited: true,
    callsUnlimited: "Non",
    roaming: "Non inclus",
    fiveG: false,
    extraServices: ["WhatsApp illimité", "Instagram illimité"],
    callHours: 3.3,
  },
  {
    id: 2,
    name: "Social Plus",
    category: "social",
    price: 69,
    internetGo: 5,
    internetLabel: "5 Go",
    callsLabel: "300 min",
    smsLabel: "200 SMS",
    mainBenefit: "Réseaux sociaux + 10 Go nuit",
    benefitIcon: "🌙",
    socialUnlimited: true,
    callsUnlimited: "Non",
    roaming: "Non inclus",
    fiveG: false,
    extraServices: ["TikTok illimité", "10 Go bonus nuit (00h-6h)"],
    callHours: 5,
  },
  {
    id: 3,
    name: "Social Max",
    category: "social",
    price: 89,
    internetGo: 8,
    internetLabel: "8 Go",
    callsLabel: "Illimité vers inwi",
    smsLabel: "200 SMS",
    mainBenefit: "Réseaux sociaux + appels inwi illimités",
    benefitIcon: "📱",
    socialUnlimited: true,
    callsUnlimited: "Vers inwi",
    roaming: "Non inclus",
    fiveG: false,
    extraServices: ["YouTube illimité", "Appels illimités vers inwi"],
    callHours: 20,
  },
  {
    id: 4,
    name: "Data Light",
    category: "internet",
    price: 59,
    internetGo: 6,
    internetLabel: "6 Go",
    callsLabel: "100 min",
    smsLabel: "50 SMS",
    mainBenefit: "Bonus 2 Go la nuit",
    benefitIcon: "🌐",
    socialUnlimited: false,
    callsUnlimited: "Non",
    roaming: "Non inclus",
    fiveG: false,
    extraServices: ["2 Go bonus nuit"],
    callHours: 1.7,
  },
  {
    id: 5,
    name: "Data Medium",
    category: "internet",
    price: 99,
    internetGo: 15,
    internetLabel: "15 Go",
    callsLabel: "200 min",
    smsLabel: "100 SMS",
    mainBenefit: "Internet 5G inclus",
    benefitIcon: "⚡",
    socialUnlimited: false,
    callsUnlimited: "Non",
    roaming: "Non inclus",
    fiveG: true,
    extraServices: ["5G incluse"],
    callHours: 3.3,
  },
  {
    id: 6,
    name: "Data Max",
    category: "internet",
    price: 149,
    internetGo: 30,
    internetLabel: "30 Go",
    callsLabel: "300 min",
    smsLabel: "200 SMS",
    mainBenefit: "Partage de connexion inclus",
    benefitIcon: "🔗",
    socialUnlimited: false,
    callsUnlimited: "Non",
    roaming: "Non inclus",
    fiveG: true,
    extraServices: ["5G incluse", "Partage de connexion (hotspot)"],
    callHours: 5,
  },
  {
    id: 7,
    name: "Data XL",
    category: "internet",
    price: 199,
    internetGo: 60,
    internetLabel: "60 Go",
    callsLabel: "Illimité vers inwi",
    smsLabel: "300 SMS",
    mainBenefit: "60 Go + appels inwi illimités",
    benefitIcon: "🌐",
    socialUnlimited: false,
    callsUnlimited: "Vers inwi",
    roaming: "Non inclus",
    fiveG: true,
    extraServices: ["5G incluse", "Appels illimités vers inwi"],
    callHours: 20,
  },
  {
    id: 8,
    name: "Appels Eco",
    category: "appels",
    price: 49,
    internetGo: 1,
    internetLabel: "1 Go",
    callsLabel: "Illimité vers inwi",
    smsLabel: "50 SMS",
    mainBenefit: "Appels illimités vers inwi",
    benefitIcon: "📞",
    socialUnlimited: false,
    callsUnlimited: "Vers inwi",
    roaming: "Non inclus",
    fiveG: false,
    extraServices: ["Appels illimités vers inwi"],
    callHours: 15,
  },
  {
    id: 9,
    name: "Appels Plus",
    category: "appels",
    price: 79,
    internetGo: 3,
    internetLabel: "3 Go",
    callsLabel: "Illimité national",
    smsLabel: "100 SMS",
    mainBenefit: "Appels illimités tous opérateurs",
    benefitIcon: "📞",
    socialUnlimited: false,
    callsUnlimited: "National",
    roaming: "Non inclus",
    fiveG: false,
    extraServices: ["Appels illimités national"],
    callHours: 25,
  },
  {
    id: 10,
    name: "Appels Max",
    category: "appels",
    price: 119,
    internetGo: 8,
    internetLabel: "8 Go",
    callsLabel: "Illimité + 60 min intl.",
    smsLabel: "200 SMS",
    mainBenefit: "60 min à l'international incluses",
    benefitIcon: "✈️",
    socialUnlimited: false,
    callsUnlimited: "National",
    roaming: "Non inclus",
    fiveG: false,
    extraServices: ["Appels illimités national", "60 min international"],
    callHours: 30,
  },
  {
    id: 11,
    name: "Illimité Essentiel",
    category: "illimite",
    price: 129,
    internetGo: 20,
    internetLabel: "20 Go",
    callsLabel: "Illimité",
    smsLabel: "Illimité",
    mainBenefit: "Appels & SMS illimités",
    benefitIcon: "♾️",
    socialUnlimited: true,
    callsUnlimited: "Total",
    roaming: "Maghreb",
    fiveG: false,
    extraServices: ["SMS illimités", "Roaming Maghreb léger"],
    callHours: 40,
  },
  {
    id: 12,
    name: "Illimité Confort",
    category: "illimite",
    price: 179,
    internetGo: 40,
    internetLabel: "40 Go",
    callsLabel: "Illimité",
    smsLabel: "Illimité",
    mainBenefit: "5G + roaming Europe",
    benefitIcon: "🌍",
    socialUnlimited: true,
    callsUnlimited: "Total",
    roaming: "Europe",
    fiveG: true,
    extraServices: ["SMS illimités", "Roaming Europe", "5G incluse"],
    callHours: 50,
  },
  {
    id: 13,
    name: "Illimité Premium",
    category: "illimite",
    price: 249,
    internetGo: 80,
    internetLabel: "80 Go",
    callsLabel: "Illimité",
    smsLabel: "Illimité",
    mainBenefit: "Roaming international inclus",
    benefitIcon: "🌎",
    socialUnlimited: true,
    callsUnlimited: "Total",
    roaming: "International",
    fiveG: true,
    extraServices: ["SMS illimités", "Roaming international", "5G incluse", "Cloud 50 Go"],
    callHours: 60,
  },
  {
    id: 14,
    name: "Illimité Ultra",
    category: "illimite",
    price: 349,
    internetGo: 130,
    internetLabel: "Internet illimité",
    callsLabel: "Illimité",
    smsLabel: "Illimité",
    mainBenefit: "Tout illimité + services premium",
    benefitIcon: "👑",
    socialUnlimited: true,
    callsUnlimited: "Total",
    roaming: "Monde",
    fiveG: true,
    extraServices: [
      "SMS illimités",
      "Roaming monde",
      "5G incluse",
      "Abonnement streaming inclus",
      "Cloud 200 Go",
    ],
    callHours: 80,
  },
];
